### ISSUE TITLE
create API views to `GET` lectures and `GET` a single lecture

### ISSUE THREAD

**Issue by drjova** [cern-sis/cern-academic-training#2]
Create an REST API using [django rest framework](https://www.django-rest-framework.org)

```
GET /lectures
{
  results: [
    {},
  ]
}
```

```
GET /lectures/:id
{
}
```

**Comment by fanimator12** [comment]
REST API available on new branch 'rest_api' with both requesting lectures and a single lecture with id.

![Screenshot_1](https://user-images.githubusercontent.com/56829184/139645318-77cbcaf3-088b-4ecd-9bf4-951e2147bfdf.png)
![Screenshot_2](https://user-images.githubusercontent.com/56829184/139645324-3b815580-2f41-4d7d-8109-9cbfff18e5cf.png)
