### ISSUE TITLE
search improvements

### ISSUE THREAD

**Issue by drjova** [cern-sis/cern-academic-training#34]
**Requirements**

Allow search to work with the following fields:

* speaker
* sponsor
* series
* subject_category

We have also to adjust the boost for this fields.

**Acceptance**
* `series`
  * search for `CERN Academic Training Lecture - 316` (series) should get `lecture_id : 294504` lecture as first result
  *  search for `series:CERN Academic Training Lecture - 316` (series) should get `lecture_id : 294504` lecture as the **only** result

* `sponsor`
  * search for `Massimo Giovannozzi` should get only results for sponsor `Massimo Giovannozzi
  * search for `sponsor:Massimo Giovannozzi` should get only results for sponsor `Massimo Giovannozzi

* `speaker`
  *   search for `Maria Dimou` should get only results for speaker `Maria Dimou`
  *  search for `speaker:Maria Dimou` should get only results for speaker `Maria Dimou`

* `subject_category`
  * search for `Particle Physics`  should get only results for subject_category `Particle Physics`
  *  search for `subject_category:Particle Physics` should get only results for subject_category `Particle Physics`

**Comment by Neodia** [comment]
The ones without the field names should be ES boosted
