### ISSUE TITLE
multiple videos in a record

### ISSUE THREAD

**Issue by drjova** [cern-sis/cern-academic-training#49]
Currently we don't support multiple videos per record, an example https://cds.cern.ch/record/341905 and it gives an error https://academictraining.cern.ch/lectures/341905

**Comment by drjova** [comment]
# Tech Notes

## Harvester:

* We need to add here https://github.com/cern-sis/cern-academic-training/blob/master/harvest/harvest/spiders/cds_spider.py#L267-L269 a simalr selector which gets `'.//datafield[@tag=852]/subfield[@code="8"]/text()'` and if it's not empty at the end https://github.com/cern-sis/cern-academic-training/blob/master/harvest/harvest/spiders/cds_spider.py#L279-L280 we add the type `multivideo`
* For testing https://github.com/cern-sis/cern-academic-training/tree/master/harvest/tests we could get the marcxml from https://cds.cern.ch/record/341905 and check if `multivideo` is populated.

**Comment by mariadimou** [comment]
Thank you @drjova !
What I said at noon today (about taking the Indico event number from the _Mediaarchive_ path in the URI doesn't apply for these very old videos... I saw https://cds.cern.ch/record/341905/export/xm?ln=en
No trace of any _event number_ in the path... 
Sorry... and thanks very much for putting up with the challenge!
Maria

**Comment by mariadimou** [comment]
@drjova about our mattermost discussion: 
Just putting here the behaviour of the academictraining.cern.ch web site for this example record:
It shows misleading error https://academictraining.cern.ch/lectures/341905/
for existing record https://cds.cern.ch/record/341905

The fact is, as you know, I have to answer M.Mangano and wonder if we can have a date for this fix, please. 

Thank you very  much!
Maria

**Comment by drjova** [comment]
@mariadimou could you please send us the message to display for the missing video parts?

**Comment by mariadimou** [comment]
Yes, thanks! It was in  my _todo_ list: 

The suggestion is to show the first of the >1 in the CDS record and write 
"For more videos from the same lecture series, please visit https://cds.cern.ch/record/THE_EXACT_NUMBER"

Example: https://academictraining.cern.ch/lectures/341905/ the message would say:

For more videos from the same lecture series, please visit https://cds.cern.ch/record/341905

Thank you very much! Brilliant idea to keep the CDS record number also on the URI of our site! Thank you!

**Comment by mariadimou** [comment]
@drjova I hope you are well! 
At the last discussion I suggested that you show the first of multiple videos and you offer the link to CDS for viewing the rest of the videos from the same (old) record. You said this is easier to do. 
Right now, the record used as example for this misleading error is totally broken. It just gives a blank page. 
Please test it with https://academictraining.cern.ch/lectures/341905/

The rest of the search for "Mangano" is even more broken!
Please check https://academictraining.cern.ch/search/?search=mangano&page=1

I used Firefox and Chromium.

Thanks!
Maria

**Comment by drjova** [comment]
video parts are now available on academictraining.cern.ch
