### ISSUE TITLE
google meta tags

### ISSUE THREAD

**Issue by drjova** [cern-sis/cern-academic-training#50]

**Comment by mariadimou** [comment]
Thank you @drjova for taking this up. 
I put here the reference to https://its.cern.ch/jira/projects/ATWEB/issues/ATWEB-62
in case its contents are helpful ...  keywords in the site's head section etc...

**Comment by mariadimou** [comment]
Dear @drjova ,
I look forward and need urgently to find our site coming up first when one searches. It is still not the case for Google, although it comes FIRST with Duckduckgo!?!?!?

The comments I've put in JIRA ticket (above) is:
- absence of Keywords in the source
- If one puts in google "site:academictraining.cern.ch" then our site comes up, which means that it IS indexed indeed. Why doesn't it come up!?!?!?

thanks in advance for your advice
Maria

**Comment by drjova** [comment]
**Tech Notes:**

* Add the following google meta tags:


```html
<meta name="google-site-verification" content="FCSlkOUl1kpidRHQJ59lR5RUeZtJ4AgjqLZ64FpeAjg">
```

* For all the pages we should add a `description` tag from the `abstract` (160 chars max) of each record, if there is no a record page (i.e. search, about etc) we should add the following:

```html
<meta name="description" content="The CERN Academic Training lectures cover physics and technology research results, as well as leading-edge news from other disciplines. Past lectures often present a great historical value.">
```


**Acceptance:**
* The tags should change everytime a user navigates to a different page
* If I open a specific lecture (for example https://academictraining.cern.ch/lectures/2827044) it should have the following meta tags:

```html
<title>REMOTE: An overview of the FLUKA particle transport code and its graphical user interface Flair | CERN Academic Training</title>
<meta name="description" content="An overview shall be presented of FLUKA, a general-purpose code for the Monte Carlo simulation of radiation transport, and of its powerful graphical ....">
```

* if I open the home page it should have the following:
```html
<title>Home | CERN Academic Training</title>
<meta name="description" content="The CERN Academic Training lectures cover physics and technology research results, as well as leading-edge news from other disciplines. Past lectures often present a great historical value.">
```
