### ISSUE TITLE
Player's play button should be in the middle

### ISSUE THREAD

**Issue by drjova** [cern-sis/cern-academic-training#57]
https://academictraining.cern.ch/lectures/341905/

<img width="1001" alt="Screenshot 2022-11-04 at 14 18 46" src="https://user-images.githubusercontent.com/4287772/199982094-b5f309db-5bb4-42a6-918a-113b094fd8fd.png">

**Comment by victoria-parker** [comment]
Hi @drjova! Could I work on this issue? Thank you!

**Comment by drjova** [comment]
> Hi @drjova! Could I work on this issue? Thank you!

Hi @victoria-parker, thank you for your offer. It is an open-source project, so please feel free to contribute!
